
#instructions pour gérer les conteneurs :
 
services: #represente une image
   my_ubuntu:
    image: celtak/ubuntu-ping-ip
    container_name: celtak_ubuntu
#Le conteneur  my_ubuntu est lance, l'image utilisée etle nom du conteneur
